import Header from "@/src/components/header/Header";
import BackgroundImagePrez from "@/src/components/presentation/image";
import ProjectPrez from "@/src/components/project/projectSlider";
import axios from "axios";
import { ThemeProvider } from "../src/components/MTUI";
import "./globals.css";

export const metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let repos;
  await axios
    .get("https://api.github.com/users/montenegroPatrick/repos", {
      Authorization: "Bearer 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",
    })
    .then((res) => (repos = res.data))
    .catch((err) => Error());
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          <Header />
          <BackgroundImagePrez />
          {children}
          <ProjectPrez repos={repos} />
        </body>
      </html>
    </ThemeProvider>
  );
}
