import Footer from "@/src/components/footer/footer";
import Header from "@/src/components/header/Header";
import "./globals.css";
import { cantarell, deliciousHandrawn, robotoMono } from "./fonts";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";

export const metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let repos;
  const api = axios.create({
    baseURL: "https://api.github.com",
    headers: {
      Authorization: "Bearer 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",
    },
  });
  await api
    .get("/users/montenegroPatrick/repos?visibility=public")
    .then((res) => (repos = res.data))
    .catch((err) => Error());
  return (
    <html
      lang="en"
      className={`${robotoMono.variable} ${cantarell.variable} ${deliciousHandrawn.variable}`}
    >
      <body className={`w-screen bg-gray-300 dark:bg-black font-mono`}>
        {children}
      </body>
    </html>
  );
}
