import Header from "@/src/components/header/Header";
import ProjectPrez from "@/src/components/project/projectSlider";
import axios from "axios";
import { ThemeProvider } from "../src/components/MTUI";
import "./globals.css";

export const metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let repos;
  await axios
    .get("https://api.github.com/users/montenegroPatrick/repos")
    .then((res) => (repos = res.data));
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          <Header />
          {children}
          <ProjectPrez repos={repos} />
        </body>
      </html>
    </ThemeProvider>
  );
}
